export const FETCH_EXPEDITION = 'FETCH_EXPEDITION';
export const FETCH_EXPEDITIONS = 'FETCH_EXPEDITIONS';
export const REQUEST_LOADING_EXPEDITION = 'REQUEST_LOADING_EXPEDITION';
export const REQUEST_REJECTED_EXPEDITION = 'REQUEST_REJECTED_EXPEDITION';