export const FETCH_ECOTURISMO = 'FETCH_ECOTURISMO';
export const FETCH_ECOTURISMOS = 'FETCH_ECOTURISMOS';
export const REQUEST_LOADING_ECOTURISMO = 'REQUEST_LOADING_ECOTURISMO';
export const REQUEST_REJECTED_ECOTURISMO = 'REQUEST_REJECTED_ECOTURISMO';
