export const REQUEST_LOADING_NEWSLETTER = 'REQUEST_LOADING_NEWSLETTER';
export const REQUEST_REJECTED_NEWSLETTER = 'REQUEST_REJECTED_NEWSLETTER';
export const REQUEST_FULFILLED_NEWSLETTER = 'REQUEST_FULFILLED_NEWSLETTER';