export const FETCH_IMERSAO = 'FETCH_IMERSAO';
export const FETCH_IMERSOES = 'FETCH_IMERSOES';
export const REQUEST_LOADING_IMERSAO = 'REQUEST_LOADING_IMERSAO';
export const REQUEST_REJECTED_IMERSAO = 'REQUEST_REJECTED_IMERSAO';
