export const REQUEST_LOADING_SUBSCRIBE = 'REQUEST_LOADING_SUBSCRIBE';
export const REQUEST_REJECTED_SUBSCRIBE = 'REQUEST_REJECTED_SUBSCRIBE';
export const REQUEST_FULFILLED_SUBSCRIBE = 'REQUEST_FULFILLED_SUBSCRIBE';