export const FETCH_VOLUNTURISMO = 'FETCH_VOLUNTURISMO';
export const FETCH_VOLUNTURISMOS = 'FETCH_VOLUNTURISMOS';
export const REQUEST_LOADING_VOLUNTURISMO = 'REQUEST_LOADING_VOLUNTURISMO';
export const REQUEST_REJECTED_VOLUNTURISMO = 'REQUEST_REJECTED_VOLUNTURISMO';
