export const FETCH_EXPERIENCE = 'FETCH_EXPERIENCE';
export const FETCH_EXPERIENCES = 'FETCH_EXPERIENCES';
export const REQUEST_LOADING_EXPERIENCE = 'REQUEST_LOADING_EXPERIENCE';
export const REQUEST_REJECTED_EXPERIENCE = 'REQUEST_REJECTED_EXPERIENCE';