export const REQUEST_LOADING_CONTACT = 'REQUEST_LOADING_CONTACT';
export const REQUEST_REJECTED_CONTACT = 'REQUEST_REJECTED_CONTACT';
export const REQUEST_FULFILLED_CONTACT = 'REQUEST_FULFILLED_CONTACT';